### ISSUE TITLE
Table undefined. tableName=TEST

### ISSUE THREAD

**Issue by zaheershaik** [gaodazhu/phoenix-client#3]
I constantly get this issue when I try to use node.js code. Any help?

The same select works from JDBC though.

var phoenix = require("phoenix-client");
var db = new phoenix("jdbc:phoenix:SERVERNAME:PORT","admin","admin",["-Xmx1024m"]);

db.query('select \* from "TABLE_NAME" limit 10',function success(dataJson){
    console.info(dataJson);
},function error(e){
    console.error(e);
});

15/02/23 15:57:22 INFO client.HConnectionManager$HConnectionImplementation: Closing master protocol: MasterService
15/02/23 15:57:22 INFO client.HConnectionManager$HConnectionImplementation: Closing zookeeper sessionid=0x4b6c250b1e3cf5
15/02/23 15:57:22 INFO zookeeper.ZooKeeper: Session: 0x4b6c250b1e3cf5 closed
15/02/23 15:57:22 INFO zookeeper.ClientCnxn: EventThread shut down
15/02/23 15:57:23 ERROR pool.DruidDataSource: init datasource error
org.apache.phoenix.schema.TableNotFoundException: ERROR 1012 (42M03): Table undefined. tableName=TEST
    at org.apache.phoenix.compile.FromCompiler$BaseColumnResolver.createTableRef(FromCompiler.java:276)
    at org.apache.phoenix.compile.FromCompiler$SingleTableColumnResolver.<init>(FromCompiler.java:193)
    at org.apache.phoenix.compile.FromCompiler.getResolverForQuery(FromCompiler.java:150)
    at org.apache.phoenix.jdbc.PhoenixStatement$ExecutableSelectStatement.compilePlan(PhoenixStatement.java:262)
    at org.apache.phoenix.jdbc.PhoenixStatement$ExecutableSelectStatement.compilePlan(PhoenixStatement.java:253)
    at org.apache.phoenix.jdbc.PhoenixStatement.executeQuery(PhoenixStatement.java:199)
    at org.apache.phoenix.jdbc.PhoenixStatement.executeQuery(PhoenixStatement.java:895)
    at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1212)
    at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1422)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:604)
    at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:878)
    at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:874)
    at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:97)
    at com.mlsc.DBClient.query(DBClient.java:134)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
15/02/23 15:57:23 ERROR pool.DruidDataSource: dataSource init error
org.apache.phoenix.schema.TableNotFoundException: ERROR 1012 (42M03): Table undefined. tableName=TEST
    at org.apache.phoenix.compile.FromCompiler$BaseColumnResolver.createTableRef(FromCompiler.java:276)
    at org.apache.phoenix.compile.FromCompiler$SingleTableColumnResolver.<init>(FromCompiler.java:193)
    at org.apache.phoenix.compile.FromCompiler.getResolverForQuery(FromCompiler.java:150)
    at org.apache.phoenix.jdbc.PhoenixStatement$ExecutableSelectStatement.compilePlan(PhoenixStatement.java:262)
    at org.apache.phoenix.jdbc.PhoenixStatement$ExecutableSelectStatement.compilePlan(PhoenixStatement.java:253)
    at org.apache.phoenix.jdbc.PhoenixStatement.executeQuery(PhoenixStatement.java:199)
    at org.apache.phoenix.jdbc.PhoenixStatement.executeQuery(PhoenixStatement.java:895)
    at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1212)
    at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1422)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:604)
    at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:878)
    at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:874)
    at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:97)
    at com.mlsc.DBClient.query(DBClient.java:134)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
15/02/23 15:57:23 INFO pool.DruidDataSource: {dataSource-1} inited
org.apache.phoenix.schema.TableNotFoundException: ERROR 1012 (42M03): Table undefined. tableName=TEST
    at org.apache.phoenix.compile.FromCompiler$BaseColumnResolver.createTableRef(FromCompiler.java:276)
    at org.apache.phoenix.compile.FromCompiler$SingleTableColumnResolver.<init>(FromCompiler.java:193)
    at org.apache.phoenix.compile.FromCompiler.getResolverForQuery(FromCompiler.java:150)
    at org.apache.phoenix.jdbc.PhoenixStatement$ExecutableSelectStatement.compilePlan(PhoenixStatement.java:262)
    at org.apache.phoenix.jdbc.PhoenixStatement$ExecutableSelectStatement.compilePlan(PhoenixStatement.java:253)
    at org.apache.phoenix.jdbc.PhoenixStatement.executeQuery(PhoenixStatement.java:199)
    at org.apache.phoenix.jdbc.PhoenixStatement.executeQuery(PhoenixStatement.java:895)
    at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1212)
    at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1422)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:604)
    at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:878)
    at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:874)
    at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:97)
    at com.mlsc.DBClient.query(DBClient.java:134)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
[TypeError: Cannot read property '0' of null]

Process finished with exit code 0

**Comment by gaodazhu** [comment]
remove double quote from the table name

**Comment by zaheershaik** [comment]
Sorry, that didn't help. I've tried the following and they result in the same error.

'select \* from TABLE_NAME limit 10'

"select \* from 'TABLE_NAME' limit 10"

'select \* from \'TABLE_NAME\' limit 10'

**Comment by gaodazhu** [comment]
Oh,sorry! Please add an empty table named test in phoenix ! It is used as validationQuery

**Comment by coresilver** [comment]
After I append TEST table to Phoenix query server, It does work!
And I try to query some table which exist in Phoenix but it returns this:

**\* Loaded lib and start JDBC ...
**\* Create JBDC complete, start query ...
java.sql.SQLException: validationQuery didn't return a row
        at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1214)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1422)
        at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:604)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:878)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:874)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:97)
        at com.mlsc.DBClient.query(DBClient.java:134)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
[TypeError: Cannot read property '0' of null]

----- My query

db.query("select \* from US_POPULATION limit 1",
function success(dataJson)
{
        console.info(dataJson);
},
function error(e){
        console.info(e);
});

I am back to check US_POPULATION table and found two records in the table.

How do I solve this problem ?

Thanks,
Rocky

**Comment by zfz** [comment]
@coresilver Have upersert a row to your test table in Phoenix? I encountered the "validationQuery" error, then I tried after inserting a row in my test table, it worked.
